build:
  nodes:
    coverage:
      tests:
        override:
          - command: 'make tests'
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'