build:
  nodes:
    coverage:
      tests:
        override:
          - command: 'coverage run -m pytest tests'
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'