FROM gcr.io/oss-fuzz-base/base-builder-python
RUN apt-get update
RUN pip3 install hypothesis
#RUN apt-get update && apt-get install -y ...    # Install required packages to build your project.
#COPY . $SRC/<project_name>                      # Copy your project's source code.
#WORKDIR $SRC/<project_name>                     # Working directory for build.sh.
#COPY ./.clusterfuzzlite/build.sh $SRC/           # Copy build.sh into $SRC dir.
